/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/past/builtins/misc.py:45: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  from imp import reload
/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/bleach_whitelist/bleach_whitelist.py:3: DeprecationWarning: bleach-whitelist has been renamed bleach-allowlist. It will not receive further updates under the old name. See https://pypi.org/project/bleach-allowlist
  warnings.warn(
/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/past/builtins/misc.py:45: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  from imp import reload
/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/past/builtins/misc.py:45: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  from imp import reload
/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/bleach_whitelist/bleach_whitelist.py:3: DeprecationWarning: bleach-whitelist has been renamed bleach-allowlist. It will not receive further updates under the old name. See https://pypi.org/project/bleach-allowlist
  warnings.warn(
/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/bleach_whitelist/bleach_whitelist.py:3: DeprecationWarning: bleach-whitelist has been renamed bleach-allowlist. It will not receive further updates under the old name. See https://pypi.org/project/bleach-allowlist
  warnings.warn(
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/redis/client.py", line 3718, in run
    self.run()
  File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/redis/client.py", line 3718, in run
    self.run()
  File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/redis/client.py", line 3718, in run
    pubsub.get_message(ignore_subscribe_messages=True,
  File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/redis/client.py", line 3617, in get_message
    pubsub.get_message(ignore_subscribe_messages=True,
  File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/redis/client.py", line 3617, in get_message
    response = self.parse_response(block=False, timeout=timeout)
  File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/redis/client.py", line 3503, in parse_response
    response = self.parse_response(block=False, timeout=timeout)
  File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/redis/client.py", line 3503, in parse_response
    if not block and not conn.can_read(timeout=timeout):
  File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/redis/connection.py", line 734, in can_read
    if not block and not conn.can_read(timeout=timeout):
  File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/redis/connection.py", line 734, in can_read
    pubsub.get_message(ignore_subscribe_messages=True,
  File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/redis/client.py", line 3617, in get_message
    response = self.parse_response(block=False, timeout=timeout)
  File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/redis/client.py", line 3503, in parse_response
    if not block and not conn.can_read(timeout=timeout):
  File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/redis/connection.py", line 734, in can_read
    return self._parser.can_read(timeout)
  File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/redis/connection.py", line 416, in can_read
    return self.read_from_socket(timeout=timeout,
  File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/redis/connection.py", line 429, in read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.
    return self._parser.can_read(timeout)
  File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/redis/connection.py", line 416, in can_read
    return self.read_from_socket(timeout=timeout,
  File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/redis/connection.py", line 429, in read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.
    return self._parser.can_read(timeout)
  File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/redis/connection.py", line 416, in can_read
    return self.read_from_socket(timeout=timeout,
  File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/redis/connection.py", line 429, in read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.
/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/past/builtins/misc.py:45: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  from imp import reload
/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/bleach_whitelist/bleach_whitelist.py:3: DeprecationWarning: bleach-whitelist has been renamed bleach-allowlist. It will not receive further updates under the old name. See https://pypi.org/project/bleach-allowlist
  warnings.warn(
/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/past/builtins/misc.py:45: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  from imp import reload
/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/past/builtins/misc.py:45: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  from imp import reload
/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/bleach_whitelist/bleach_whitelist.py:3: DeprecationWarning: bleach-whitelist has been renamed bleach-allowlist. It will not receive further updates under the old name. See https://pypi.org/project/bleach-allowlist
  warnings.warn(
/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/bleach_whitelist/bleach_whitelist.py:3: DeprecationWarning: bleach-whitelist has been renamed bleach-allowlist. It will not receive further updates under the old name. See https://pypi.org/project/bleach-allowlist
  warnings.warn(
/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/past/builtins/misc.py:45: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  from imp import reload
/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/past/builtins/misc.py:45: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  from imp import reload
/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/past/builtins/misc.py:45: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  from imp import reload
/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/bleach_whitelist/bleach_whitelist.py:3: DeprecationWarning: bleach-whitelist has been renamed bleach-allowlist. It will not receive further updates under the old name. See https://pypi.org/project/bleach-allowlist
  warnings.warn(
/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/bleach_whitelist/bleach_whitelist.py:3: DeprecationWarning: bleach-whitelist has been renamed bleach-allowlist. It will not receive further updates under the old name. See https://pypi.org/project/bleach-allowlist
  warnings.warn(
/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/bleach_whitelist/bleach_whitelist.py:3: DeprecationWarning: bleach-whitelist has been renamed bleach-allowlist. It will not receive further updates under the old name. See https://pypi.org/project/bleach-allowlist
  warnings.warn(
/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/past/builtins/misc.py:45: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  from imp import reload
/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/bleach_whitelist/bleach_whitelist.py:3: DeprecationWarning: bleach-whitelist has been renamed bleach-allowlist. It will not receive further updates under the old name. See https://pypi.org/project/bleach-allowlist
  warnings.warn(
/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/past/builtins/misc.py:45: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  from imp import reload
/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/bleach_whitelist/bleach_whitelist.py:3: DeprecationWarning: bleach-whitelist has been renamed bleach-allowlist. It will not receive further updates under the old name. See https://pypi.org/project/bleach-allowlist
  warnings.warn(
/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/past/builtins/misc.py:45: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  from imp import reload
/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/bleach_whitelist/bleach_whitelist.py:3: DeprecationWarning: bleach-whitelist has been renamed bleach-allowlist. It will not receive further updates under the old name. See https://pypi.org/project/bleach-allowlist
  warnings.warn(
fatal: No remote configured to list refs from.
/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/past/builtins/misc.py:45: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  from imp import reload
/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/bleach_whitelist/bleach_whitelist.py:3: DeprecationWarning: bleach-whitelist has been renamed bleach-allowlist. It will not receive further updates under the old name. See https://pypi.org/project/bleach-allowlist
  warnings.warn(
/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/past/builtins/misc.py:45: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  from imp import reload
/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/past/builtins/misc.py:45: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  from imp import reload
/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/bleach_whitelist/bleach_whitelist.py:3: DeprecationWarning: bleach-whitelist has been renamed bleach-allowlist. It will not receive further updates under the old name. See https://pypi.org/project/bleach-allowlist
  warnings.warn(
/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/bleach_whitelist/bleach_whitelist.py:3: DeprecationWarning: bleach-whitelist has been renamed bleach-allowlist. It will not receive further updates under the old name. See https://pypi.org/project/bleach-allowlist
  warnings.warn(
/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/past/builtins/misc.py:45: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  from imp import reload
/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/past/builtins/misc.py:45: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  from imp import reload
/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/bleach_whitelist/bleach_whitelist.py:3: DeprecationWarning: bleach-whitelist has been renamed bleach-allowlist. It will not receive further updates under the old name. See https://pypi.org/project/bleach-allowlist
  warnings.warn(
/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/bleach_whitelist/bleach_whitelist.py:3: DeprecationWarning: bleach-whitelist has been renamed bleach-allowlist. It will not receive further updates under the old name. See https://pypi.org/project/bleach-allowlist
  warnings.warn(
/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/past/builtins/misc.py:45: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  from imp import reload
/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/bleach_whitelist/bleach_whitelist.py:3: DeprecationWarning: bleach-whitelist has been renamed bleach-allowlist. It will not receive further updates under the old name. See https://pypi.org/project/bleach-allowlist
  warnings.warn(
fatal: No remote configured to list refs from.
Traceback (most recent call last):
  File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/redis/connection.py", line 559, in connect
    sock = self._connect()
  File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/redis/connection.py", line 615, in _connect
    raise err
  File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/redis/connection.py", line 603, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/sameer/Documents/sameer/apps/frappe/frappe/utils/bench_helper.py", line 104, in <module>
    main()
  File "/home/sameer/Documents/sameer/apps/frappe/frappe/utils/bench_helper.py", line 19, in main
    click.Group(commands=commands)(prog_name='bench')
  File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/sameer/Documents/sameer/apps/frappe/frappe/commands/scheduler.py", line 178, in start_worker
    start_worker(queue, quiet = quiet)
  File "/home/sameer/Documents/sameer/apps/frappe/frappe/utils/background_jobs.py", line 155, in start_worker
    Worker(queues, name=get_worker_name(queue)).work(logging_level = logging_level)
  File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/rq/worker.py", line 627, in work
    self.unsubscribe()
  File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/rq/worker.py", line 532, in unsubscribe
    self.pubsub.unsubscribe()
  File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/redis/client.py", line 3600, in unsubscribe
    return self.execute_command('UNSUBSCRIBE', *args)
  File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/redis/client.py", line 3466, in execute_command
    self.connection = self.connection_pool.get_connection(
  File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/redis/connection.py", line 1192, in get_connection
    connection.connect()
  File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/redis/connection.py", line 563, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to localhost:11000. Connection refused.
Traceback (most recent call last):
Exception in thread   File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/redis/connection.py", line 559, in connect
Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
        sock = self._connect()self.run()

  File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/redis/connection.py", line 615, in _connect
  File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/redis/client.py", line 3718, in run
    raise err
  File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/redis/connection.py", line 603, in _connect
    sock.connect(socket_address)
ConnectionRefusedError    : pubsub.get_message(ignore_subscribe_messages=True,[Errno 111] Connection refused

  File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/redis/client.py", line 3617, in get_message

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,    
response = self.parse_response(block=False, timeout=timeout)  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code

  File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/redis/client.py", line 3503, in parse_response
    exec(code, run_globals)
      File "/home/sameer/Documents/sameer/apps/frappe/frappe/utils/bench_helper.py", line 104, in <module>
if not block and not conn.can_read(timeout=timeout):
  File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/redis/connection.py", line 734, in can_read
    main()    
return self._parser.can_read(timeout)  File "/home/sameer/Documents/sameer/apps/frappe/frappe/utils/bench_helper.py", line 19, in main

  File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/redis/connection.py", line 416, in can_read
        click.Group(commands=commands)(prog_name='bench')return self.read_from_socket(timeout=timeout,

  File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/click/core.py", line 829, in __call__
  File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/redis/connection.py", line 429, in read_from_socket
    return self.main(*args, **kwargs)    
raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)  File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/click/core.py", line 782, in main

redis.exceptions.ConnectionError: Connection closed by server.    
rv = self.invoke(ctx)
  File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/sameer/Documents/sameer/apps/frappe/frappe/commands/scheduler.py", line 178, in start_worker
    start_worker(queue, quiet = quiet)
  File "/home/sameer/Documents/sameer/apps/frappe/frappe/utils/background_jobs.py", line 155, in start_worker
    Worker(queues, name=get_worker_name(queue)).work(logging_level = logging_level)
  File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/rq/worker.py", line 626, in work
    self.register_death()
  File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/rq/worker.py", line 326, in register_death
    p.execute()
  File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/redis/client.py", line 4012, in execute
    conn = self.connection_pool.get_connection('MULTI',
  File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/redis/connection.py", line 1192, in get_connection
    connection.connect()
  File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/redis/connection.py", line 563, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to localhost:11000. Connection refused.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/redis/client.py", line 3718, in run
    pubsub.get_message(ignore_subscribe_messages=True,
  File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/redis/client.py", line 3617, in get_message
    response = self.parse_response(block=False, timeout=timeout)
  File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/redis/client.py", line 3503, in parse_response
    if not block and not conn.can_read(timeout=timeout):
  File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/redis/connection.py", line 734, in can_read
    return self._parser.can_read(timeout)
  File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/redis/connection.py", line 416, in can_read
    return self.read_from_socket(timeout=timeout,
  File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/redis/connection.py", line 429, in read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.
Traceback (most recent call last):
  File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/redis/connection.py", line 559, in connect
    sock = self._connect()
  File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/redis/connection.py", line 615, in _connect
    raise err
  File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/redis/connection.py", line 603, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/sameer/Documents/sameer/apps/frappe/frappe/utils/bench_helper.py", line 104, in <module>
    main()
  File "/home/sameer/Documents/sameer/apps/frappe/frappe/utils/bench_helper.py", line 19, in main
    click.Group(commands=commands)(prog_name='bench')
  File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/sameer/Documents/sameer/apps/frappe/frappe/commands/scheduler.py", line 178, in start_worker
    start_worker(queue, quiet = quiet)
  File "/home/sameer/Documents/sameer/apps/frappe/frappe/utils/background_jobs.py", line 155, in start_worker
    Worker(queues, name=get_worker_name(queue)).work(logging_level = logging_level)
  File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/rq/worker.py", line 626, in work
    self.register_death()
  File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/rq/worker.py", line 326, in register_death
    p.execute()
  File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/redis/client.py", line 4012, in execute
    conn = self.connection_pool.get_connection('MULTI',
  File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/redis/connection.py", line 1192, in get_connection
    connection.connect()
  File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/redis/connection.py", line 563, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to localhost:11000. Connection refused.
/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/past/builtins/misc.py:45: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  from imp import reload
/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/past/builtins/misc.py:45: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  from imp import reload
/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/bleach_whitelist/bleach_whitelist.py:3: DeprecationWarning: bleach-whitelist has been renamed bleach-allowlist. It will not receive further updates under the old name. See https://pypi.org/project/bleach-allowlist
  warnings.warn(
/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/bleach_whitelist/bleach_whitelist.py:3: DeprecationWarning: bleach-whitelist has been renamed bleach-allowlist. It will not receive further updates under the old name. See https://pypi.org/project/bleach-allowlist
  warnings.warn(
/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/past/builtins/misc.py:45: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  from imp import reload
/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/bleach_whitelist/bleach_whitelist.py:3: DeprecationWarning: bleach-whitelist has been renamed bleach-allowlist. It will not receive further updates under the old name. See https://pypi.org/project/bleach-allowlist
  warnings.warn(
/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/past/builtins/misc.py:45: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  from imp import reload
/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/bleach_whitelist/bleach_whitelist.py:3: DeprecationWarning: bleach-whitelist has been renamed bleach-allowlist. It will not receive further updates under the old name. See https://pypi.org/project/bleach-allowlist
  warnings.warn(
/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/past/builtins/misc.py:45: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  from imp import reload
/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/past/builtins/misc.py:45: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  from imp import reload
/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/bleach_whitelist/bleach_whitelist.py:3: DeprecationWarning: bleach-whitelist has been renamed bleach-allowlist. It will not receive further updates under the old name. See https://pypi.org/project/bleach-allowlist
  warnings.warn(
/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/bleach_whitelist/bleach_whitelist.py:3: DeprecationWarning: bleach-whitelist has been renamed bleach-allowlist. It will not receive further updates under the old name. See https://pypi.org/project/bleach-allowlist
  warnings.warn(
Traceback (most recent call last):
  File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/redis/connection.py", line 559, in connect
    sock = self._connect()
  File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/redis/connection.py", line 615, in _connect
    raise err
  File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/redis/connection.py", line 603, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/sameer/Documents/sameer/apps/frappe/frappe/utils/bench_helper.py", line 104, in <module>
    main()
  File "/home/sameer/Documents/sameer/apps/frappe/frappe/utils/bench_helper.py", line 19, in main
    click.Group(commands=commands)(prog_name='bench')
  File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/sameer/Documents/sameer/apps/frappe/frappe/commands/scheduler.py", line 178, in start_worker
    start_worker(queue, quiet = quiet)
  File "/home/sameer/Documents/sameer/apps/frappe/frappe/utils/background_jobs.py", line 155, in start_worker
    Worker(queues, name=get_worker_name(queue)).work(logging_level = logging_level)
  File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/rq/worker.py", line 627, in work
    self.unsubscribe()
  File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/rq/worker.py", line 532, in unsubscribe
    self.pubsub.unsubscribe()
  File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/redis/client.py", line 3600, in unsubscribe
    return self.execute_command('UNSUBSCRIBE', *args)
  File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/redis/client.py", line 3466, in execute_command
    self.connection = self.connection_pool.get_connection(
  File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/redis/connection.py", line 1192, in get_connection
    connection.connect()
  File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/redis/connection.py", line 563, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to localhost:11000. Connection refused.
Exception in thread Exception in thread Thread-1Thread-1:
:
Traceback (most recent call last):
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
        self.run()
  File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/redis/client.py", line 3718, in run
    pubsub.get_message(ignore_subscribe_messages=True,
  File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/redis/client.py", line 3617, in get_message
    response = self.parse_response(block=False, timeout=timeout)
  File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/redis/client.py", line 3503, in parse_response
    if not block and not conn.can_read(timeout=timeout):
  File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/redis/connection.py", line 734, in can_read
    return self._parser.can_read(timeout)
  File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/redis/connection.py", line 416, in can_read
    return self.read_from_socket(timeout=timeout,
  File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/redis/connection.py", line 429, in read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
self.run()
redis.exceptions.ConnectionError: Connection closed by server.
  File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/redis/client.py", line 3718, in run
    pubsub.get_message(ignore_subscribe_messages=True,
  File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/redis/client.py", line 3617, in get_message
    response = self.parse_response(block=False, timeout=timeout)
  File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/redis/client.py", line 3503, in parse_response
    if not block and not conn.can_read(timeout=timeout):
Traceback (most recent call last):
  File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/redis/connection.py", line 734, in can_read
  File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/redis/connection.py", line 559, in connect
    return self._parser.can_read(timeout)
      File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/redis/connection.py", line 416, in can_read
sock = self._connect()
  File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/redis/connection.py", line 615, in _connect
        raise err
  File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/redis/connection.py", line 603, in _connect
return self.read_from_socket(timeout=timeout,
      File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/redis/connection.py", line 429, in read_from_socket
sock.connect(socket_address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
      File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError    : return _run_code(code, main_globals, None,Connection closed by server.

  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/sameer/Documents/sameer/apps/frappe/frappe/utils/bench_helper.py", line 104, in <module>
    main()
  File "/home/sameer/Documents/sameer/apps/frappe/frappe/utils/bench_helper.py", line 19, in main
    click.Group(commands=commands)(prog_name='bench')
  File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/sameer/Documents/sameer/apps/frappe/frappe/commands/scheduler.py", line 178, in start_worker
    start_worker(queue, quiet = quiet)
  File "/home/sameer/Documents/sameer/apps/frappe/frappe/utils/background_jobs.py", line 155, in start_worker
    Worker(queues, name=get_worker_name(queue)).work(logging_level = logging_level)
  File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/rq/worker.py", line 626, in work
    self.register_death()
  File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/rq/worker.py", line 326, in register_death
    p.execute()
  File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/redis/client.py", line 4012, in execute
    conn = self.connection_pool.get_connection('MULTI',
  File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/redis/connection.py", line 1192, in get_connection
    connection.connect()
  File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/redis/connection.py", line 563, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to localhost:11000. Connection refused.
Traceback (most recent call last):
  File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/redis/connection.py", line 559, in connect
    sock = self._connect()
  File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/redis/connection.py", line 615, in _connect
    raise err
  File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/redis/connection.py", line 603, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/sameer/Documents/sameer/apps/frappe/frappe/utils/bench_helper.py", line 104, in <module>
    main()
  File "/home/sameer/Documents/sameer/apps/frappe/frappe/utils/bench_helper.py", line 19, in main
    click.Group(commands=commands)(prog_name='bench')
  File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/sameer/Documents/sameer/apps/frappe/frappe/commands/scheduler.py", line 178, in start_worker
    start_worker(queue, quiet = quiet)
  File "/home/sameer/Documents/sameer/apps/frappe/frappe/utils/background_jobs.py", line 155, in start_worker
    Worker(queues, name=get_worker_name(queue)).work(logging_level = logging_level)
  File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/rq/worker.py", line 626, in work
    self.register_death()
  File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/rq/worker.py", line 326, in register_death
    p.execute()
  File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/redis/client.py", line 4012, in execute
    conn = self.connection_pool.get_connection('MULTI',
  File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/redis/connection.py", line 1192, in get_connection
    connection.connect()
  File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/redis/connection.py", line 563, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to localhost:11000. Connection refused.
/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/past/builtins/misc.py:45: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  from imp import reload
/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/past/builtins/misc.py:45: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  from imp import reload
/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/bleach_whitelist/bleach_whitelist.py:3: DeprecationWarning: bleach-whitelist has been renamed bleach-allowlist. It will not receive further updates under the old name. See https://pypi.org/project/bleach-allowlist
  warnings.warn(
/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/past/builtins/misc.py:45: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  from imp import reload
/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/bleach_whitelist/bleach_whitelist.py:3: DeprecationWarning: bleach-whitelist has been renamed bleach-allowlist. It will not receive further updates under the old name. See https://pypi.org/project/bleach-allowlist
  warnings.warn(
/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/bleach_whitelist/bleach_whitelist.py:3: DeprecationWarning: bleach-whitelist has been renamed bleach-allowlist. It will not receive further updates under the old name. See https://pypi.org/project/bleach-allowlist
  warnings.warn(
Traceback (most recent call last):
  File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/redis/connection.py", line 559, in connect
    sock = self._connect()
  File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/redis/connection.py", line 615, in _connect
    raise err
  File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/redis/connection.py", line 603, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/sameer/Documents/sameer/apps/frappe/frappe/utils/bench_helper.py", line 104, in <module>
    main()
  File "/home/sameer/Documents/sameer/apps/frappe/frappe/utils/bench_helper.py", line 19, in main
    click.Group(commands=commands)(prog_name='bench')
  File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/sameer/Documents/sameer/apps/frappe/frappe/commands/scheduler.py", line 178, in start_worker
    start_worker(queue, quiet = quiet)
  File "/home/sameer/Documents/sameer/apps/frappe/frappe/utils/background_jobs.py", line 155, in start_worker
    Worker(queues, name=get_worker_name(queue)).work(logging_level = logging_level)
  File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/rq/worker.py", line 627, in work
    self.unsubscribe()
  File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/rq/worker.py", line 532, in unsubscribe
    self.pubsub.unsubscribe()
  File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/redis/client.py", line 3600, in unsubscribe
    return self.execute_command('UNSUBSCRIBE', *args)
  File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/redis/client.py", line 3466, in execute_command
    self.connection = self.connection_pool.get_connection(
  File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/redis/connection.py", line 1192, in get_connection
    connection.connect()
  File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/redis/connection.py", line 563, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to localhost:11000. Connection refused.
Exception in thread Exception in thread Thread-1:
Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/redis/client.py", line 3718, in run
    pubsub.get_message(ignore_subscribe_messages=True,
  File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/redis/client.py", line 3617, in get_message
    response = self.parse_response(block=False, timeout=timeout)
  File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/redis/client.py", line 3503, in parse_response
    if not block and not conn.can_read(timeout=timeout):
  File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/redis/connection.py", line 734, in can_read
    return self._parser.can_read(timeout)
  File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/redis/connection.py", line 416, in can_read
    return self.read_from_socket(timeout=timeout,
  File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/redis/connection.py", line 429, in read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.
    self.run()
  File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/redis/client.py", line 3718, in run
    pubsub.get_message(ignore_subscribe_messages=True,
  File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/redis/client.py", line 3617, in get_message
    response = self.parse_response(block=False, timeout=timeout)
  File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/redis/client.py", line 3503, in parse_response
    if not block and not conn.can_read(timeout=timeout):
  File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/redis/connection.py", line 734, in can_read
    return self._parser.can_read(timeout)
  File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/redis/connection.py", line 416, in can_read
    return self.read_from_socket(timeout=timeout,
  File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/redis/connection.py", line 429, in read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.
Traceback (most recent call last):
  File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/redis/connection.py", line 559, in connect
    sock = self._connect()
  File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/redis/connection.py", line 615, in _connect
    raise err
  File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/redis/connection.py", line 603, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/sameer/Documents/sameer/apps/frappe/frappe/utils/bench_helper.py", line 104, in <module>
    main()
  File "/home/sameer/Documents/sameer/apps/frappe/frappe/utils/bench_helper.py", line 19, in main
    click.Group(commands=commands)(prog_name='bench')
  File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/sameer/Documents/sameer/apps/frappe/frappe/commands/scheduler.py", line 178, in start_worker
    start_worker(queue, quiet = quiet)
  File "/home/sameer/Documents/sameer/apps/frappe/frappe/utils/background_jobs.py", line 155, in start_worker
    Worker(queues, name=get_worker_name(queue)).work(logging_level = logging_level)
  File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/rq/worker.py", line 626, in work
    self.register_death()
  File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/rq/worker.py", line 326, in register_death
    p.execute()
  File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/redis/client.py", line 4012, in execute
    conn = self.connection_pool.get_connection('MULTI',
  File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/redis/connection.py", line 1192, in get_connection
Traceback (most recent call last):
  File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/redis/connection.py", line 559, in connect
    connection.connect()
  File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/redis/connection.py", line 563, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to localhost:11000. Connection refused.
    sock = self._connect()
  File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/redis/connection.py", line 615, in _connect
    raise err
  File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/redis/connection.py", line 603, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/sameer/Documents/sameer/apps/frappe/frappe/utils/bench_helper.py", line 104, in <module>
    main()
  File "/home/sameer/Documents/sameer/apps/frappe/frappe/utils/bench_helper.py", line 19, in main
    click.Group(commands=commands)(prog_name='bench')
  File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/sameer/Documents/sameer/apps/frappe/frappe/commands/scheduler.py", line 178, in start_worker
    start_worker(queue, quiet = quiet)
  File "/home/sameer/Documents/sameer/apps/frappe/frappe/utils/background_jobs.py", line 155, in start_worker
    Worker(queues, name=get_worker_name(queue)).work(logging_level = logging_level)
  File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/rq/worker.py", line 626, in work
    self.register_death()
  File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/rq/worker.py", line 326, in register_death
    p.execute()
  File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/redis/client.py", line 4012, in execute
    conn = self.connection_pool.get_connection('MULTI',
  File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/redis/connection.py", line 1192, in get_connection
    connection.connect()
  File "/home/sameer/Documents/sameer/env/lib/python3.8/site-packages/redis/connection.py", line 563, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to localhost:11000. Connection refused.
